/** Declaration file generated by dts-gen */

declare module 'winston-better-sqlite3';

declare class winston_better_sqlite3 {
    constructor(...args: any[]);

    log(...args: any[]): void;

}

declare namespace winston_better_sqlite3 {
    class LegacyTransportStream {
        constructor(options: any);

        close(): void;

    }

}

